# Generated by Django 4.2.13 on 2024-06-03 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_answer_id_alter_question_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("nutrtion", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="recipes"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
