# Generated by Django 4.2.13 on 2024-06-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_recipe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
